# Use the official OpenJDK 11 image as base image
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the packaged jar file into the container at /app
COPY target/HelloWorld-0.0.1-SNAPSHOT.jar /app

# Expose the port the application runs on
EXPOSE 8081

# Define the command to run your application
CMD ["java", "-jar", "HelloWorld-0.0.1-SNAPSHOT.jar.jar"]
